### PR TITLE
Fix 12am/pm Issue and Separate Time Functions

### LINKED ISSUE #45: Event Card: 12:00pm displays incorrectly
Screen Shot 2020-05-08 at 1 02 46 PM

### PR DESCRIPTION
**Pull request by steets250**
Resolves #45

### CODE REVIEW

File: src/utils.tsx [hunk 1]
```diff
@@ -37,3 +39,71 @@ export const getAbsoluteURL = (str: string): string | undefined => {
...
+
+  const processTime = (h: number, m: number): string => {
+    let time = '';
+
+    if (h === 0 || h === 24) {
+      time = '12';
+    } else if (h < 13) {
+      time = h.toString();
+    } else if (h < 24) {
+      time = (h % 12).toString();
```
Comment (leestanley) [inline src/utils.tsx:95]: Use tolocaletimestring

**Comment by StormFireFox1** [comment]
Task linked: [CU-8gk416 Fix 12pm edgecase with Event Card](https://app.clickup.com/t/8gk416)
